### ISSUE TITLE
Switching back to user "Cacahuete" when using any commands

### ISSUE THREAD

**Issue by ArtichOwO** [CacahueteSansSel/leterminal#7] opened 2021-03-04 16:03 UTC
Same as https://github.com/CacahueteSansSel/leterminal/issues/5, but reverse

**Comment by CacahueteSansSel** [comment] 2021-03-05 07:22
I was not able to reproduce this bug with my version, but I will rework the entire system this evening (can't do that now).

**Comment by CacahueteSansSel** [comment] 2021-03-06 14:46
Normally fixed in 3013b18. You can reopen this issue if it shows up again

**Closed as completed by CacahueteSansSel** 2021-03-06 14:46 UTC
